env: hallway

env_args:
  map_name: "hallway"
  n_agents: 3
  state_numbers: [4, 6, 10]
  reward_win: 1
  obs_last_action: False
  state_last_action: False
  print_rew: False
  is_print: False
  print_steps: 1000

learner_log_interval: 10000
log_interval: 50000
runner_log_interval: 10000
t_max: 2050000
test_interval: 10000
test_nepisode: 100
test_greedy: True