env: "lbf"

env_args:
  map_name: 20x20-10p-6f-s1
  field_size: 20
  players: 10
  max_food: 6
  force_coop: False
  sight: 1
  is_print: False
  need_render: False
  max_player_level: 2

test_greedy: True
test_nepisode: 100
test_interval: 50000
log_interval: 50000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
