env: "lbf"

env_args:
  map_name: 11x11-6p-4f-s1
  field_size: 11
  players: 6
  max_food: 4
  force_coop: False
  sight: 1
  is_print: False
  need_render: False
  max_player_level: 2

test_greedy: True
test_nepisode: 100
test_interval: 50000
log_interval: 50000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
